name: SnapMD
favicon: null
layout_spectrum: 0.24477
typography_spectrum: 0.39766
title: 'spinox : virtual clinic'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ce4527'
    - '#ffffff'
    - '#000000'
    - '#f7a487'
    - '#602315'
  brandStrength: 0.5
  lightness: 0.875
  saturation: 0.5625
  rhythmicContrast: 0
purpose: []
