name: SnapMD
favicon: null
layout_spectrum: 0.24477
typography_spectrum: 0.39766
title: SnapMD - Virtual Care Management Telemedicine
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ce4527'
    - '#ffffff'
    - '#000000'
    - '#f7a487'
    - '#602315'
  brandStrength: 0.5
  lightness: 0.8892383519560099
  saturation: 0
  rhythmicContrast: 0.05815168865956366
purpose: []
